dev:
\tair -Xms256m -Xmx256m # (or just) go run ./cmd/server
gql:
\tgo run github.com/99designs/gqlgen generate
wire:
\tgo run github.com/google/wire/cmd/wire ./internal/wire
test:
\tgo test ./...
lint:
\tgolangci-lint run
